[project]
name = "discord-bots"
version = "0.1.0"
description = "Python discord bots"
authors = [{"name" = "Tim Klein Nijenhuis", "email" = "tim@hetorus.nl"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12,<3.13"
packages = []
dependencies = [
    "discord-py>=2.7.1",
    "requests>=2.34.2",
]

[tool.black]
line-length = 120

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-watcher>=0.6.3",
]
